### ISSUE TITLE
Optimize problem list with redux

### ISSUE THREAD

**Issue by KoeInoue** [KoeInoue/writing-frontend#129]
# ToDo

- [x] Add reload button
- [x] Store problem list in redux
- [x] Store/Update/Delete a problem in redux when changed
- [x] Only fetch when the redux is empty
- [x] Order by date

# Definition of Completed

-
