### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by KoeInoue** [KoeInoue/writing-frontend#163]
# ToDo

Code generator
- [ ] Add codegen https://the-guild.dev/graphql/codegen/docs/getting-started

React Query
- [ ] Replace to react query
- [ ] Add Suspense of react query

Components & hooks https://zenn.dev/uhyo/articles/useeffect-taught-by-extremist
- [ ] Extract API request to hooks
- [ ] Avoid using useEffect
- [ ] minimize page components

Admin
- [ ] Fix admin page

# Definition of Completed

-
