### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by KoeInoue** [KoeInoue/writing-frontend#56]
# ToDo

- [x] Integrate Nextjs app directory [zenn](https://zenn.dev/azukiazusa/articles/next-js-app-dir-tutorial) ※Check Amplify supports
- [ ] Split components based on Atomic design
- [ ] Create hooks
- [ ] https://zenn.dev/uhyo/articles/useeffect-taught-by-extremist

# Definition of Completed

-
